### ISSUE TITLE
Different pageid for the same MP

### ISSUE THREAD

**Issue by resulumit** [saschagobel/legislatoR#4]
Hi,

This is about the data, not the package.

I have just noticed that John Grogan (House of Commons) has two different _pageid_ (427345, 10021735). I am not sure if this is a useful piece of information, but just in case it is, I wanted to note it here.

I have also noticed that some of the datapoints for the latter observation (pageid = 10021735) is wrong according to his wikipedia page (https://en.wikipedia.org/wiki/John_Grogan_(politician)). These include, for example, his date of birth.

Thank you for this great resource.

Best,
Resul

**Comment by saschagobel** [comment]
Dear Resul,

thank you for bringing this to our attention. This should be fixed now. There was a wrong link to the Wikipedia biography of John Grogan (the American journalist and non-fiction writer, pageid = 10021735) instead of John Grogan (politician, pageid = 427345) on the Wikipedia page that lists all members of the 57th UK House of Commons. This is also fixed on Wikipedia now, see https://en.wikipedia.org/w/index.php?title=List_of_MPs_elected_in_the_2017_United_Kingdom_general_election&diff=967943360&oldid=966284283

Please close this issue if this solves the problem.

Best,
Sascha
